### ISSUE TITLE
python error on install of AppDaemon

### ISSUE THREAD

**Issue by rottison** [lostinthebuild/S01E01-washer-notifier#1]
22:33:00] INFO: Starting AppDaemon...
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 384, in main
    admain.main()
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 264, in main
    appdaemon["disable_apps"] = False
TypeError: 'str' object does not support item assignment

**Comment by madaboutcode** [comment]
@rottison can you also post your `appdaemon.yaml`. I went through the line where the error occurs in the [app daemon code](https://github.com/home-assistant/appdaemon/blob/master/appdaemon/__main__.py#L262). the `appdaemon` object comes from the config. So I'm wondering if there is a problem with the config.

**Comment by rottison** [comment]
secrets: /config/secrets.yaml
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.xx.xxx:8123/
      token: !secret token
hadashboard:
  dash_url: http://192.168.xx.xxx:5050
  dash_dir: /config/appdaemon/dashboards
appdaemon: rott
hadashboard:
  dash_url: http://192.168.xx.xxx:5050

**Comment by rottison** [comment]
Also for the config section on the install addon page in the Config section I have
system_packages: []
python_packages: []
init_commands: []

**Comment by rottison** [comment]
hello?

**Comment by madaboutcode** [comment]
Sorry, been really sick 🤢  the past couple of days. 

From the `appdaemon.yaml` file, can you remove the line

```
appdaemon: rott
```
(_what's that for?_)

I'm guessing that line overwrites the config for `appdaemon` declared couple of lines before and sets the `appdaemon` value as the string "rott". This must be causing the problem during your AppDaemon startup.

**Comment by rottison** [comment]
rott is the Pc name that HA is on

**Comment by madaboutcode** [comment]
> rott is the Pc name that HA is on

Then, is it that line required? I never tried to configure to the appdaemon dashboard. So i'm not familiar with its configuration.

**Comment by rottison** [comment]
I have it working I deleted every thing that had to do with appdaemon and reinstalled it now it works
Thank you for getting back to me

**Comment by madaboutcode** [comment]
👍
